"""

Revision ID: 234779818471
Revises: 677dfd367f11
Create Date: 2026-02-22 19:20:03.236789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "234779818471"
down_revision: Union[str, Sequence[str], None] = "677dfd367f11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("brewing", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "brewing", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("brewing", "user_id")
    # ### end Alembic commands ###
