"""add user_id to brewing

Revision ID: 3c8cc0d749d8
Revises: 677dfd367f11
Create Date: 2026-02-22 19:30:08.326370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8cc0d749d8'
down_revision: Union[str, Sequence[str], None] = '677dfd367f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brewing', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'brewing', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brewing', type_='foreignkey')
    op.drop_column('brewing', 'user_id')
    # ### end Alembic commands ###
