"""

Revision ID: 5f81996ffd76
Revises: 7d8db3fe188a
Create Date: 2026-03-15 13:53:46.495985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f81996ffd76'
down_revision: Union[str, Sequence[str], None] = '7d8db3fe188a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brewing', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brewing', 'rating')
    # ### end Alembic commands ###
