"""

Revision ID: b56fdf031dda
Revises: fc26978b8874
Create Date: 2026-03-29 08:47:53.644122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b56fdf031dda'
down_revision: Union[str, Sequence[str], None] = 'fc26978b8874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brewings', sa.Column('grind_size', sa.String(), nullable=False))
    op.add_column('brewings', sa.Column('water_volume', sa.Integer(), nullable=False))
    op.add_column('brewings', sa.Column('coffee_amount', sa.Integer(), nullable=False))
    op.alter_column('brewings', 'method',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brewings', 'method',
               existing_type=sa.String(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('brewings', 'coffee_amount')
    op.drop_column('brewings', 'water_volume')
    op.drop_column('brewings', 'grind_size')
    # ### end Alembic commands ###
