packages:
  - packages/*

allowBuilds:
  "@swc/core": true
  esbuild: true
  msw: true

catalog:
  oxlint: ^1.76.0

catalogMode: prefer

catalogs:
  auth:
    better-auth: ^1.6.25
  db:
    drizzle-orm: 1.0.0-rc.4
    pg: ^8.23.0
    "@types/pg": ^8.23.1
    drizzle-kit: 1.0.0-rc.4

cleanupUnusedCatalogs: true
