packages:
  - packages/*
  - tooling/*

allowBuilds:
  '@swc/core': true
  esbuild: true
  msw: true

catalog:
  oxlint: ^1.76.0

catalogMode: prefer

catalogs:
  auth:
    better-auth: ^1.6.25

cleanupUnusedCatalogs: true
