/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as SignupRouteImport } from "./routes/signup"
import { Route as BrewingsIndexRouteImport } from "./routes/brewings/index"
import { Route as BrewingsNewRouteImport } from "./routes/brewings/new"
import { Route as CoffeesIndexRouteImport } from "./routes/coffees/index"
import { Route as CoffeesNewRouteImport } from "./routes/coffees/new"
import { Route as BrewingsBrewingIdIndexRouteImport } from "./routes/brewings/$brewingId/index"
import { Route as BrewingsBrewingIdEditRouteImport } from "./routes/brewings/$brewingId/edit"
import { Route as CoffeesCoffeeIdIndexRouteImport } from "./routes/coffees/$coffeeId/index"
import { Route as CoffeesCoffeeIdEditRouteImport } from "./routes/coffees/$coffeeId/edit"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any)
const BrewingsIndexRoute = BrewingsIndexRouteImport.update({
  id: "/brewings/",
  path: "/brewings/",
  getParentRoute: () => rootRouteImport,
} as any)
const BrewingsNewRoute = BrewingsNewRouteImport.update({
  id: "/brewings/new",
  path: "/brewings/new",
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeesIndexRoute = CoffeesIndexRouteImport.update({
  id: "/coffees/",
  path: "/coffees/",
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeesNewRoute = CoffeesNewRouteImport.update({
  id: "/coffees/new",
  path: "/coffees/new",
  getParentRoute: () => rootRouteImport,
} as any)
const BrewingsBrewingIdIndexRoute = BrewingsBrewingIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BrewingsBrewingIdRoute,
} as any)
const BrewingsBrewingIdEditRoute = BrewingsBrewingIdEditRouteImport.update({
  id: "/edit",
  path: "/edit",
  getParentRoute: () => BrewingsBrewingIdRoute,
} as any)
const CoffeesCoffeeIdIndexRoute = CoffeesCoffeeIdIndexRouteImport.update({
  id: "/coffees/$coffeeId/",
  path: "/coffees/$coffeeId/",
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeesCoffeeIdEditRoute = CoffeesCoffeeIdEditRouteImport.update({
  id: "/coffees/$coffeeId/edit",
  path: "/coffees/$coffeeId/edit",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/signup": typeof SignupRoute
  "/brewings/new": typeof BrewingsNewRoute
  "/coffees/new": typeof CoffeesNewRoute
  "/brewings/": typeof BrewingsIndexRoute
  "/coffees/": typeof CoffeesIndexRoute
  "/brewings/$brewingId/edit": typeof BrewingsBrewingIdEditRoute
  "/coffees/$coffeeId/edit": typeof CoffeesCoffeeIdEditRoute
  "/brewings/$brewingId/": typeof BrewingsBrewingIdIndexRoute
  "/coffees/$coffeeId/": typeof CoffeesCoffeeIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/signup": typeof SignupRoute
  "/brewings/new": typeof BrewingsNewRoute
  "/coffees/new": typeof CoffeesNewRoute
  "/brewings": typeof BrewingsIndexRoute
  "/coffees": typeof CoffeesIndexRoute
  "/brewings/$brewingId/edit": typeof BrewingsBrewingIdEditRoute
  "/coffees/$coffeeId/edit": typeof CoffeesCoffeeIdEditRoute
  "/brewings/$brewingId": typeof BrewingsBrewingIdIndexRoute
  "/coffees/$coffeeId": typeof CoffeesCoffeeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/signup": typeof SignupRoute
  "/brewings/new": typeof BrewingsNewRoute
  "/coffees/new": typeof CoffeesNewRoute
  "/brewings/": typeof BrewingsIndexRoute
  "/coffees/": typeof CoffeesIndexRoute
  "/brewings/$brewingId/edit": typeof BrewingsBrewingIdEditRoute
  "/coffees/$coffeeId/edit": typeof CoffeesCoffeeIdEditRoute
  "/brewings/$brewingId/": typeof BrewingsBrewingIdIndexRoute
  "/coffees/$coffeeId/": typeof CoffeesCoffeeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/signup"
    | "/brewings/new"
    | "/coffees/new"
    | "/brewings/"
    | "/coffees/"
    | "/brewings/$brewingId/edit"
    | "/coffees/$coffeeId/edit"
    | "/brewings/$brewingId/"
    | "/coffees/$coffeeId/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/signup"
    | "/brewings/new"
    | "/coffees/new"
    | "/brewings"
    | "/coffees"
    | "/brewings/$brewingId/edit"
    | "/coffees/$coffeeId/edit"
    | "/brewings/$brewingId"
    | "/coffees/$coffeeId"
  id:
    | "__root__"
    | "/"
    | "/login"
    | "/signup"
    | "/brewings/new"
    | "/coffees/new"
    | "/brewings/"
    | "/coffees/"
    | "/brewings/$brewingId/edit"
    | "/coffees/$coffeeId/edit"
    | "/brewings/$brewingId/"
    | "/coffees/$coffeeId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  BrewingsNewRoute: typeof BrewingsNewRoute
  CoffeesNewRoute: typeof CoffeesNewRoute
  BrewingsIndexRoute: typeof BrewingsIndexRoute
  CoffeesIndexRoute: typeof CoffeesIndexRoute
  CoffeesCoffeeIdEditRoute: typeof CoffeesCoffeeIdEditRoute
  CoffeesCoffeeIdIndexRoute: typeof CoffeesCoffeeIdIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/signup": {
      id: "/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/brewings/": {
      id: "/brewings/"
      path: "/brewings"
      fullPath: "/brewings/"
      preLoaderRoute: typeof BrewingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/brewings/new": {
      id: "/brewings/new"
      path: "/brewings/new"
      fullPath: "/brewings/new"
      preLoaderRoute: typeof BrewingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/coffees/": {
      id: "/coffees/"
      path: "/coffees"
      fullPath: "/coffees/"
      preLoaderRoute: typeof CoffeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/coffees/new": {
      id: "/coffees/new"
      path: "/coffees/new"
      fullPath: "/coffees/new"
      preLoaderRoute: typeof CoffeesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/brewings/$brewingId/": {
      id: "/brewings/$brewingId/"
      path: "/"
      fullPath: "/brewings/$brewingId/"
      preLoaderRoute: typeof BrewingsBrewingIdIndexRouteImport
      parentRoute: typeof BrewingsBrewingIdRoute
    }
    "/brewings/$brewingId/edit": {
      id: "/brewings/$brewingId/edit"
      path: "/edit"
      fullPath: "/brewings/$brewingId/edit"
      preLoaderRoute: typeof BrewingsBrewingIdEditRouteImport
      parentRoute: typeof BrewingsBrewingIdRoute
    }
    "/coffees/$coffeeId/": {
      id: "/coffees/$coffeeId/"
      path: "/coffees/$coffeeId"
      fullPath: "/coffees/$coffeeId/"
      preLoaderRoute: typeof CoffeesCoffeeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/coffees/$coffeeId/edit": {
      id: "/coffees/$coffeeId/edit"
      path: "/coffees/$coffeeId/edit"
      fullPath: "/coffees/$coffeeId/edit"
      preLoaderRoute: typeof CoffeesCoffeeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  BrewingsNewRoute: BrewingsNewRoute,
  CoffeesNewRoute: CoffeesNewRoute,
  BrewingsIndexRoute: BrewingsIndexRoute,
  CoffeesIndexRoute: CoffeesIndexRoute,
  CoffeesCoffeeIdEditRoute: CoffeesCoffeeIdEditRoute,
  CoffeesCoffeeIdIndexRoute: CoffeesCoffeeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
