/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as SignupRouteImport } from "./routes/signup"
import { Route as BrewingsIndexRouteImport } from "./routes/brewings/index"
import { Route as BrewingsBrewingIdRouteImport } from "./routes/brewings/$brewingId"
import { Route as CoffeesIndexRouteImport } from "./routes/coffees/index"
import { Route as CoffeesCoffeeIdRouteImport } from "./routes/coffees/$coffeeId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any)
const BrewingsIndexRoute = BrewingsIndexRouteImport.update({
  id: "/brewings/",
  path: "/brewings/",
  getParentRoute: () => rootRouteImport,
} as any)
const BrewingsBrewingIdRoute = BrewingsBrewingIdRouteImport.update({
  id: "/brewings/$brewingId",
  path: "/brewings/$brewingId",
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeesIndexRoute = CoffeesIndexRouteImport.update({
  id: "/coffees/",
  path: "/coffees/",
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeesCoffeeIdRoute = CoffeesCoffeeIdRouteImport.update({
  id: "/coffees/$coffeeId",
  path: "/coffees/$coffeeId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/signup": typeof SignupRoute
  "/brewings/$brewingId": typeof BrewingsBrewingIdRoute
  "/coffees/$coffeeId": typeof CoffeesCoffeeIdRoute
  "/brewings/": typeof BrewingsIndexRoute
  "/coffees/": typeof CoffeesIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/signup": typeof SignupRoute
  "/brewings/$brewingId": typeof BrewingsBrewingIdRoute
  "/coffees/$coffeeId": typeof CoffeesCoffeeIdRoute
  "/brewings": typeof BrewingsIndexRoute
  "/coffees": typeof CoffeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/signup": typeof SignupRoute
  "/brewings/$brewingId": typeof BrewingsBrewingIdRoute
  "/coffees/$coffeeId": typeof CoffeesCoffeeIdRoute
  "/brewings/": typeof BrewingsIndexRoute
  "/coffees/": typeof CoffeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/signup"
    | "/brewings/$brewingId"
    | "/coffees/$coffeeId"
    | "/brewings/"
    | "/coffees/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/signup"
    | "/brewings/$brewingId"
    | "/coffees/$coffeeId"
    | "/brewings"
    | "/coffees"
  id:
    | "__root__"
    | "/"
    | "/login"
    | "/signup"
    | "/brewings/$brewingId"
    | "/coffees/$coffeeId"
    | "/brewings/"
    | "/coffees/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  BrewingsBrewingIdRoute: typeof BrewingsBrewingIdRoute
  CoffeesCoffeeIdRoute: typeof CoffeesCoffeeIdRoute
  BrewingsIndexRoute: typeof BrewingsIndexRoute
  CoffeesIndexRoute: typeof CoffeesIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/signup": {
      id: "/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/brewings/": {
      id: "/brewings/"
      path: "/brewings"
      fullPath: "/brewings/"
      preLoaderRoute: typeof BrewingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/brewings/$brewingId": {
      id: "/brewings/$brewingId"
      path: "/brewings/$brewingId"
      fullPath: "/brewings/$brewingId"
      preLoaderRoute: typeof BrewingsBrewingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/coffees/": {
      id: "/coffees/"
      path: "/coffees"
      fullPath: "/coffees/"
      preLoaderRoute: typeof CoffeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/coffees/$coffeeId": {
      id: "/coffees/$coffeeId"
      path: "/coffees/$coffeeId"
      fullPath: "/coffees/$coffeeId"
      preLoaderRoute: typeof CoffeesCoffeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  BrewingsBrewingIdRoute: BrewingsBrewingIdRoute,
  CoffeesCoffeeIdRoute: CoffeesCoffeeIdRoute,
  BrewingsIndexRoute: BrewingsIndexRoute,
  CoffeesIndexRoute: CoffeesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
