"""

Revision ID: 050900ec4a8e
Revises: 557bcdf840b2
Create Date: 2026-04-29 22:26:26.131944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '050900ec4a8e'
down_revision: Union[str, Sequence[str], None] = '557bcdf840b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brewings', sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brewings', 'notes')
    # ### end Alembic commands ###
