"""

Revision ID: 557bcdf840b2
Revises: b56fdf031dda
Create Date: 2026-03-29 14:36:55.324537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557bcdf840b2'
down_revision: Union[str, Sequence[str], None] = 'b56fdf031dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'brewings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brewings', type_='foreignkey')
    # ### end Alembic commands ###
